POST http://localhost:5000/api/reminders
Content-Type: application/json

{
  "content": "Estudiar para la prueba",
  "important": true
}

POST http://localhost:5000/api/reminders
Content-Type: application/json

{
  "content": "Comprar pan"
}

GET http://localhost:5000/api/reminders

PATCH http://localhost:5000/api/reminders/PASTE_ID_HERE
Content-Type: application/json

{
  "content": "Estudiar Flask actualizado",
  "important": false
}

DELETE http://localhost:5000/api/reminders/PASTE_ID_HERE
